In [6]:
# приклад з конспекту
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a[1, 1])
print(a[1:, 1])
print(a[0, :2])

5
[5 8]
[1 2]


In [7]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [1]:
# зрізи (слайси)

# створюємо простий список
s = [1, 2, 3, 4, 6]

# посилання на список
d = s

# копія списку
f = s[:]
print(s)
print(d)
print(f)
print()
print(d is s)
print(f is s)

[1, 2, 3, 4, 6]
[1, 2, 3, 4, 6]
[1, 2, 3, 4, 6]

True
False


In [4]:
# зрізи з двома параметрами
s = [1, 2, 3, 4, 6]

print(s[1:-2])   # всі елементи, крім першого
print(s[-3:])  # останні 3 елемента
print(s[2:-2]) # відкидаємо перші і останні 2 елементи

[2, 3]
[3, 4, 6]
[3]


In [5]:
# зрізи з третім параметром (з кроком)
s = [1, 2, 3, 4, 6]

print(s[::2])   # парні елементи (тобто стоять на парних місцях)
print(s[1:4:2]) # елементи з першого по четвертий з кроком 2

# зріз з кроком -1
print(s[::-1])

[1, 3, 6]
[2, 4]
[6, 4, 3, 2, 1]
